server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:webshop
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        generate-ddl: true
        ddl-auto: create-drop
  liquibase:
    change-log: classpath:changelog/changelog-master.xml

logging:
  file:
    name: logs/web-shop.log
  level:
    liquibase: warn
    hu.NorbertVarga: info
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-H:mm:ssMM-dd H} %highlight(%-5level) %cyan(%logger{0}) : %msg%n"
    file: "%d{yyyy-H:mm:ssMM-dd H} %-5level %logger{0} : %msg%n"

cors-policies: http://localhost:4200, http://127.0.0.1:4200