server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;
    username: admin
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate-ddl: true
        ddl-auto: create-drop

cors-policies: http://localhost:4200, http://127.0.0.1:4200